### ISSUE TITLE
Any idea for setting ignore labels?

### ISSUE THREAD

**Issue by msson** [MSiam/TFSegmentation#24]
I intend to train suffleseg model with my own dataset which has some unnecessary parts for training. (It does not mean 'background') So I would like to make ignore label for those parts to except training.
Do you have any idea for this? I do not exactly know which part I do have to modify or remove the code.
Thanks.

**Comment by MSiam** [comment]
You can find weights.npy in the data folder you can set the ignore class weight to 0. However when I experimented with both setting the ignore class weight to 0 or including the ignore class during the training. I found the second better as the network needs to identify the pixels that are classified as ignore, otherwise it will try to classify them to the other classes.

**Comment by msson** [comment]
@MSiam I can figure it out now. Thanks.
